version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm install
      - run: node_modules/.bin/lib.json from node_modules > .~lib.json
      - run: npm test